### ISSUE TITLE
Flickering issue on UITableView

### ISSUE THREAD

**Issue by marcoscurvello** [toashd/AnimatedSegmentSwitch#3]
I added an instance of 'AnimatedSegmentSwitch'  with 4 items to a tableview headerview and as soon as I start scrolling down the thumb which highlights the selected item starts flickering really bad. The item at 0 is the only one when selected stays highlighted correctly.

**Comment by toashd** [comment]
Should be fixed with a552b89672d76d50293f80deefd8625edd792d01
